services:
  spark:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
      - '7077:7077'
    extra_hosts:
      - "host.docker.internal:192.168.40.245"
    volumes:
      - ./jars:/opt/bitnami/spark/extra-jars
      - ./spark-data:/spark-data
    user: "1001"

  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    extra_hosts:
      - "host.docker.internal:192.168.40.245"
    depends_on:
      - spark
    volumes:
      - ./jars:/opt/bitnami/spark/extra-jars
      - ./spark-data:/spark-data
    user: "1001"